In [2]:
import numpy as np
import optuna

def sphere(x):
    """
    Computes the d-dimensional Sphere function.
    :param x: np.array, shape (d,) - point at which to evaluate the function.
    :return: float - value of the Sphere function at x.
    """
    return np.sum(x ** 2)

def objective(trial):
    """
    Objective function for Bayesian optimization.
    """
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(2)])
    return sphere(x)

# Example trial object for demonstration purposes
class ExampleTrial:
    def suggest_categorical(self, name, choices):
        # For demonstration, we will just return the first choice
        return choices[0]

# Create an example trial
trial = ExampleTrial()

# Get the suggested input for the Sphere function
x = np.array([trial.suggest_categorical(f"x_{i}", list(range(-5, 6))) for i in range(2)])
# print("Suggested input:", x)
display(x)

# Compute the Sphere function value
value = sphere(x)
print("Sphere function value:", value)

array([-5, -5])

Sphere function value: 50


# カテゴリ変数上と，整数変数上での gp sampler のパフォーマンスの違い

### sphere

In [4]:
import numpy as np
import optuna
from optuna.samplers import GPSampler
from functools import partial
import matplotlib.pyplot as plt

# Define the Sphere function
def sphere(x):
    return np.sum(x ** 2)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = GPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 2
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_96999/757269048.py:24: ExperimentalWarning: GPSampler is experimental (supported from v3.6.0). The interface can change in the future.
  sampler = GPSampler(seed=seed)
[I 2024-11-16 10:40:53,509] A new study created in memory with name: no-name-478dd070-c774-43aa-958f-529145aa53c2
[I 2024-11-16 10:40:53,512] Trial 0 finished with value: 25.0 and parameters: {'x_0': 3, 'x_1': 4}. Best is trial 0 with value: 25.0.
[I 2024-11-16 10:40:53,515] Trial 1 finished with value: 0.0 and parameters: {'x_0': 0, 'x_1': 0}. Best is trial 1 with value: 0.0.
[I 2024-11-16 10:40:53,517] Trial 2 finished with value: 13.0 and parameters: {'x_0': 3, 'x_1': 2}. Best is trial 1 with value: 0.0.
[I 2024-11-16 10:40:53,520] Trial 3 finished with value: 2.0 and parameters: {'x_0': 1, 'x_1': 1}. Best is trial 1 with value: 0.0.
[I 2024-11-16 10:40:53,521] Trial 4 finished with value: 17.0 and parameters: {'x_0': -4, 'x_1': -1}. Best is trial 1 with value

Categorical Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0}

Integer Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0}


In [5]:
# Plot optimization history
optuna.visualization.plot_optimization_history(study_categorical)

In [6]:
optuna.visualization.plot_optimization_history(study_int)

In [7]:
import numpy as np
import optuna
from optuna.samplers import GPSampler
from functools import partial
import matplotlib.pyplot as plt

# Define the Sphere function
def sphere(x):
    return np.sum(x ** 2)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = GPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 5
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_96999/3423068326.py:24: ExperimentalWarning:

GPSampler is experimental (supported from v3.6.0). The interface can change in the future.

[I 2024-11-16 10:42:27,846] A new study created in memory with name: no-name-0327b7ec-fe85-4729-8061-a71e4710b88f
[I 2024-11-16 10:42:27,849] Trial 0 finished with value: 34.0 and parameters: {'x_0': 3, 'x_1': 4, 'x_2': 0, 'x_3': 0, 'x_4': 3}. Best is trial 0 with value: 34.0.
[I 2024-11-16 10:42:27,850] Trial 1 finished with value: 23.0 and parameters: {'x_0': 2, 'x_1': 1, 'x_2': 1, 'x_3': -4, 'x_4': -1}. Best is trial 1 with value: 23.0.
[I 2024-11-16 10:42:27,851] Trial 2 finished with value: 60.0 and parameters: {'x_0': 3, 'x_1': -4, 'x_2': 3, 'x_3': 1, 'x_4': 5}. Best is trial 1 with value: 23.0.
[I 2024-11-16 10:42:27,853] Trial 3 finished with value: 55.0 and parameters: {'x_0': -5, 'x_1': 3, 'x_2': 1, 'x_3': -2, 'x_4': -4}. Best is trial 1 with value: 23.0.
[I 2024-11-16 10:42:27,855]

Categorical Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0, 'x_2': 0, 'x_3': 0, 'x_4': 0}

Integer Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0, 'x_2': 0, 'x_3': 0, 'x_4': 0}


In [8]:
optuna.visualization.plot_optimization_history(study_categorical)

In [9]:
optuna.visualization.plot_optimization_history(study_int)

### ackley

In [12]:
import numpy as np
import optuna
from optuna.samplers import GPSampler
from functools import partial
import matplotlib.pyplot as plt

def ackley(x):
    """
    Computes the d-dimensional Ackley function.
    :param x: np.array, shape (d,) - point at which to evaluate the function.
    :return: float - value of the Ackley function at x.
    """
    a = 20
    b = 0.2
    c = 2 * np.pi
    d = len(x)
    sum1 = -a * np.exp(-b * np.sqrt(np.sum(x ** 2) / d))
    sum2 = -np.exp(np.sum(np.cos(c * x)) / d)
    return sum1 + sum2 + a + np.exp(1)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = GPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 2
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_96999/2496229485.py:34: ExperimentalWarning:

GPSampler is experimental (supported from v3.6.0). The interface can change in the future.

[I 2024-11-16 11:03:23,850] A new study created in memory with name: no-name-3d06c237-729f-4b8d-8d06-860264d52364
[I 2024-11-16 11:03:23,851] Trial 0 finished with value: 25.0 and parameters: {'x_0': 3, 'x_1': 4}. Best is trial 0 with value: 25.0.
[I 2024-11-16 11:03:23,852] Trial 1 finished with value: 0.0 and parameters: {'x_0': 0, 'x_1': 0}. Best is trial 1 with value: 0.0.
[I 2024-11-16 11:03:23,852] Trial 2 finished with value: 13.0 and parameters: {'x_0': 3, 'x_1': 2}. Best is trial 1 with value: 0.0.
[I 2024-11-16 11:03:23,853] Trial 3 finished with value: 2.0 and parameters: {'x_0': 1, 'x_1': 1}. Best is trial 1 with value: 0.0.
[I 2024-11-16 11:03:23,854] Trial 4 finished with value: 17.0 and parameters: {'x_0': -4, 'x_1': -1}. Best is trial 1 with value: 0.0.
[I 2024-11-16 11:03:23,

Categorical Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0}

Integer Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0}


In [13]:
optuna.visualization.plot_optimization_history(study_categorical)

In [14]:
optuna.visualization.plot_optimization_history(study_int)

In [11]:
import numpy as np
import optuna
from optuna.samplers import GPSampler
from functools import partial
import matplotlib.pyplot as plt

def ackley(x):
    """
    Computes the d-dimensional Ackley function.
    :param x: np.array, shape (d,) - point at which to evaluate the function.
    :return: float - value of the Ackley function at x.
    """
    a = 20
    b = 0.2
    c = 2 * np.pi
    d = len(x)
    sum1 = -a * np.exp(-b * np.sqrt(np.sum(x ** 2) / d))
    sum2 = -np.exp(np.sum(np.cos(c * x)) / d)
    return sum1 + sum2 + a + np.exp(1)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = GPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 5
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_96999/3879657817.py:34: ExperimentalWarning:

GPSampler is experimental (supported from v3.6.0). The interface can change in the future.

[I 2024-11-16 11:02:21,997] A new study created in memory with name: no-name-2d0869b0-2480-4636-9cd4-ab11a312a99c
[I 2024-11-16 11:02:21,998] Trial 0 finished with value: 34.0 and parameters: {'x_0': 3, 'x_1': 4, 'x_2': 0, 'x_3': 0, 'x_4': 3}. Best is trial 0 with value: 34.0.
[I 2024-11-16 11:02:22,000] Trial 1 finished with value: 23.0 and parameters: {'x_0': 2, 'x_1': 1, 'x_2': 1, 'x_3': -4, 'x_4': -1}. Best is trial 1 with value: 23.0.
[I 2024-11-16 11:02:22,003] Trial 2 finished with value: 60.0 and parameters: {'x_0': 3, 'x_1': -4, 'x_2': 3, 'x_3': 1, 'x_4': 5}. Best is trial 1 with value: 23.0.
[I 2024-11-16 11:02:22,004] Trial 3 finished with value: 55.0 and parameters: {'x_0': -5, 'x_1': 3, 'x_2': 1, 'x_3': -2, 'x_4': -4}. Best is trial 1 with value: 23.0.
[I 2024-11-16 11:02:22,005]

Categorical Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0, 'x_2': 0, 'x_3': 0, 'x_4': 0}

Integer Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0, 'x_2': 0, 'x_3': 0, 'x_4': 0}


In [15]:
optuna.visualization.plot_optimization_history(study_categorical)

In [16]:
optuna.visualization.plot_optimization_history(study_int)

# optuna gp sampler のカーネル関数の理解（ハミング距離周り）

In [22]:
import torch

# 簡易版のカーネル計算関数
def simple_kernel(
    is_categorical: torch.Tensor,  # [len(params)] 各次元がカテゴリ変数かどうか
    inverse_squared_lengthscales: torch.Tensor,  # [len(params)] 各次元の逆二乗長さ尺度
    kernel_scale: float,  # カーネルスケール
    X1: torch.Tensor,  # [n_A, len(params)] 入力点集合1
    X2: torch.Tensor,  # [n_B, len(params)] 入力点集合2
) -> torch.Tensor:  # [n_A, n_B] カーネル行列
    # (1) 二乗距離 d^2 を計算
    d2 = (X1[:, None, :] - X2[None, :, :]) ** 2  # 形状: [n_A, n_B, len(params)]

    print()
    print(d2)
    print()

    # (2) カテゴリ変数の次元についてハミング距離を計算
    d2[..., is_categorical] = (d2[..., is_categorical] > 0).float() * 1

    print()
    print(d2)
    print()


    # (3) 次元ごとにスケーリングし、合計
    d2 = (d2 * inverse_squared_lengthscales).sum(dim=-1)  # 形状: [n_A, n_B]

    print()
    print(d2)
    print()

    # (4) Matérn 5/2 カーネルを適用
    sqrt5d = torch.sqrt(5 * d2)
    matern52 = (1 + sqrt5d + (5 / 3) * d2) * torch.exp(-sqrt5d)

    # (5) カーネルスケールを適用して結果を返す
    return kernel_scale * matern52


# テスト用データ
n_A, n_B = 3, 4  # 入力点集合のサイズ
len_params = 2  # パラメータの次元数

# 入力点集合1, 2
X1 = torch.tensor([[0.1, 0], [0.2, 1], [0.3, 0]], dtype=torch.float32)  # [n_A, len(params)]
X2 = torch.tensor([[0.15, 1], [0.25, 0], [0.35, 0], [0.4, 1]], dtype=torch.float32)  # [n_B, len(params)]

# 各次元がカテゴリ変数かどうかを指定
is_categorical = torch.tensor([False, True], dtype=torch.bool)

# カーネルパラメータ
inverse_squared_lengthscales = torch.tensor([10.0, 1.0], dtype=torch.float32)  # [len(params)]
kernel_scale = 1.0

# カーネル行列の計算
kernel_matrix = simple_kernel(
    is_categorical=is_categorical,
    inverse_squared_lengthscales=inverse_squared_lengthscales,
    kernel_scale=kernel_scale,
    X1=X1,
    X2=X2,
)

# 結果を出力
print("Kernel Matrix:")
print(kernel_matrix)


tensor([[[0.0025, 1.0000],
         [0.0225, 0.0000],
         [0.0625, 0.0000],
         [0.0900, 1.0000]],

        [[0.0025, 0.0000],
         [0.0025, 1.0000],
         [0.0225, 1.0000],
         [0.0400, 0.0000]],

        [[0.0225, 1.0000],
         [0.0025, 0.0000],
         [0.0025, 0.0000],
         [0.0100, 1.0000]]])


tensor([[[0.0025, 1.0000],
         [0.0225, 0.0000],
         [0.0625, 0.0000],
         [0.0900, 1.0000]],

        [[0.0025, 0.0000],
         [0.0025, 1.0000],
         [0.0225, 1.0000],
         [0.0400, 0.0000]],

        [[0.0225, 1.0000],
         [0.0025, 0.0000],
         [0.0025, 0.0000],
         [0.0100, 1.0000]]])


tensor([[1.0250, 0.2250, 0.6250, 1.9000],
        [0.0250, 1.0250, 1.2250, 0.4000],
        [1.2250, 0.0250, 0.0250, 1.1000]])

Kernel Matrix:
tensor([[0.5169, 0.8433, 0.6503, 0.3324],
        [0.9797, 0.5169, 0.4643, 0.7490],
        [0.4643, 0.9797, 0.9797, 0.4962]])


In [35]:
import torch

# 簡易版のカーネル計算関数
def simple_kernel(
    is_categorical: torch.Tensor,  # [len(params)] 各次元がカテゴリ変数かどうか
    inverse_squared_lengthscales: torch.Tensor,  # [len(params)] 各次元の逆二乗長さ尺度
    kernel_scale: float,  # カーネルスケール
    X1: torch.Tensor,  # [n_A, len(params)] 入力点集合1
    X2: torch.Tensor,  # [n_B, len(params)] 入力点集合2
) -> torch.Tensor:  # [n_A, n_B] カーネル行列
    # (1) 二乗距離 d^2 を計算
    d2 = (X1[:, None, :] - X2[None, :, :]) ** 2  # 形状: [n_A, n_B, len(params)]

    print()
    print(d2)
    print()

    # # (2) カテゴリ変数の次元についてハミング距離を計算
    # d2[..., is_categorical] = (d2[..., is_categorical] > 0).float() * 1

    # print()
    # print(d2)
    # print()


    # (3) 次元ごとにスケーリングし、合計
    d2 = (d2 * inverse_squared_lengthscales).sum(dim=-1)  # 形状: [n_A, n_B]

    print()
    print(d2)
    print()

    # (4) Matérn 5/2 カーネルを適用
    sqrt5d = torch.sqrt(5 * d2)
    matern52 = (1 + sqrt5d + (5 / 3) * d2) * torch.exp(-sqrt5d)

    # (5) カーネルスケールを適用して結果を返す
    return kernel_scale * matern52


# テスト用データ
n_A, n_B = 3, 4  # 入力点集合のサイズ
len_params = 2  # パラメータの次元数

# 入力点集合1, 2
X1 = torch.tensor([[0.1, 0], [0.2, 1], [0.3, 0]], dtype=torch.float32)  # [n_A, len(params)]
X2 = torch.tensor([[0.15, 1], [0.25, 0], [0.35, 0], [0.4, 1]], dtype=torch.float32)  # [n_B, len(params)]

# 各次元がカテゴリ変数かどうかを指定
is_categorical = torch.tensor([False, True], dtype=torch.bool)

# カーネルパラメータ
inverse_squared_lengthscales = torch.tensor([10.0, 1.0], dtype=torch.float32)  # [len(params)]
kernel_scale = 1.0

# カーネル行列の計算
kernel_matrix = simple_kernel(
    is_categorical=is_categorical,
    inverse_squared_lengthscales=inverse_squared_lengthscales,
    kernel_scale=kernel_scale,
    X1=X1,
    X2=X2,
)

# 結果を出力
print("Kernel Matrix:")
print(kernel_matrix)


tensor([[[0.0025, 1.0000],
         [0.0225, 0.0000],
         [0.0625, 0.0000],
         [0.0900, 1.0000]],

        [[0.0025, 0.0000],
         [0.0025, 1.0000],
         [0.0225, 1.0000],
         [0.0400, 0.0000]],

        [[0.0225, 1.0000],
         [0.0025, 0.0000],
         [0.0025, 0.0000],
         [0.0100, 1.0000]]])


tensor([[1.0250, 0.2250, 0.6250, 1.9000],
        [0.0250, 1.0250, 1.2250, 0.4000],
        [1.2250, 0.0250, 0.0250, 1.1000]])

Kernel Matrix:
tensor([[0.5169, 0.8433, 0.6503, 0.3324],
        [0.9797, 0.5169, 0.4643, 0.7490],
        [0.4643, 0.9797, 0.9797, 0.4962]])


# Custom GP Sampler

### sphere

In [2]:
import numpy as np
import optuna
from functools import partial
import matplotlib.pyplot as plt

from _src import CustomGPSampler


# Define the Sphere function
def sphere(x):
    return np.sum(x ** 2)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = CustomGPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 2
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_2960/532022871.py:26: ExperimentalWarning: CustomGPSampler is experimental (supported from v3.6.0). The interface can change in the future.
  sampler = CustomGPSampler(seed=seed)
[I 2024-11-16 14:38:58,466] A new study created in memory with name: no-name-fd54e45a-5b07-449a-8857-7b4846d58fd1
[I 2024-11-16 14:38:58,479] Trial 0 finished with value: 25.0 and parameters: {'x_0': 3, 'x_1': 4}. Best is trial 0 with value: 25.0.
[I 2024-11-16 14:38:58,482] Trial 1 finished with value: 0.0 and parameters: {'x_0': 0, 'x_1': 0}. Best is trial 1 with value: 0.0.
[I 2024-11-16 14:38:58,487] Trial 2 finished with value: 13.0 and parameters: {'x_0': 3, 'x_1': 2}. Best is trial 1 with value: 0.0.
[I 2024-11-16 14:38:58,489] Trial 3 finished with value: 2.0 and parameters: {'x_0': 1, 'x_1': 1}. Best is trial 1 with value: 0.0.
[I 2024-11-16 14:38:58,491] Trial 4 finished with value: 17.0 and parameters: {'x_0': -4, 'x_1': -1}. Best is trial 1

Categorical Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0}

Integer Inputs:
Best value: 0.0
Best params: {'x_0': 0, 'x_1': 0}


In [3]:
optuna.visualization.plot_optimization_history(study_categorical)

In [4]:
optuna.visualization.plot_optimization_history(study_int)

In [5]:
import numpy as np
import optuna
from functools import partial
import matplotlib.pyplot as plt

from _src import CustomGPSampler


# Define the Sphere function
def sphere(x):
    return np.sum(x ** 2)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = CustomGPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 5
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_2960/1327529152.py:26: ExperimentalWarning:

CustomGPSampler is experimental (supported from v3.6.0). The interface can change in the future.

[I 2024-11-16 14:41:03,705] A new study created in memory with name: no-name-9179658f-a8e4-47bf-a50d-ce0b2619a734
[I 2024-11-16 14:41:03,711] Trial 0 finished with value: 34.0 and parameters: {'x_0': 3, 'x_1': 4, 'x_2': 0, 'x_3': 0, 'x_4': 3}. Best is trial 0 with value: 34.0.
[I 2024-11-16 14:41:03,713] Trial 1 finished with value: 23.0 and parameters: {'x_0': 2, 'x_1': 1, 'x_2': 1, 'x_3': -4, 'x_4': -1}. Best is trial 1 with value: 23.0.
[I 2024-11-16 14:41:03,716] Trial 2 finished with value: 60.0 and parameters: {'x_0': 3, 'x_1': -4, 'x_2': 3, 'x_3': 1, 'x_4': 5}. Best is trial 1 with value: 23.0.
[I 2024-11-16 14:41:03,718] Trial 3 finished with value: 55.0 and parameters: {'x_0': -5, 'x_1': 3, 'x_2': 1, 'x_3': -2, 'x_4': -4}. Best is trial 1 with value: 23.0.
[I 2024-11-16 14:41:03

Categorical Inputs:
Best value: 1.0
Best params: {'x_0': 0, 'x_1': 0, 'x_2': -1, 'x_3': 0, 'x_4': 0}

Integer Inputs:
Best value: 6.0
Best params: {'x_0': 1, 'x_1': 0, 'x_2': 0, 'x_3': -2, 'x_4': 1}


In [6]:
optuna.visualization.plot_optimization_history(study_categorical)

In [7]:
optuna.visualization.plot_optimization_history(study_int)

In [ ]:
import numpy as np
import optuna
from functools import partial
import matplotlib.pyplot as plt

from _src import CustomGPSampler


# Define the Sphere function
def sphere(x):
    return np.sum(x ** 2)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return sphere(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return sphere(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = CustomGPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 2
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

### ackley

In [14]:
import numpy as np
import optuna
from functools import partial

from _src import CustomGPSampler


def ackley(x):
    """
    Computes the d-dimensional Ackley function.
    :param x: np.array, shape (d,) - point at which to evaluate the function.
    :return: float - value of the Ackley function at x.
    """
    a = 20
    b = 0.2
    c = 2 * np.pi
    d = len(x)
    sum1 = -a * np.exp(-b * np.sqrt(np.sum(x ** 2) / d))
    sum2 = -np.exp(np.sum(np.cos(c * x)) / d)
    return sum1 + sum2 + a + np.exp(1)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return ackley(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return ackley(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = CustomGPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 2
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_2960/3609794130.py:35: ExperimentalWarning:

CustomGPSampler is experimental (supported from v3.6.0). The interface can change in the future.

[I 2024-11-16 14:49:12,258] A new study created in memory with name: no-name-7541ebbe-e3ee-481c-a2b2-a2cad8b3ac38
[I 2024-11-16 14:49:12,262] Trial 0 finished with value: 10.138626172095204 and parameters: {'x_0': 3, 'x_1': 4}. Best is trial 0 with value: 10.138626172095204.
[I 2024-11-16 14:49:12,263] Trial 1 finished with value: 4.440892098500626e-16 and parameters: {'x_0': 0, 'x_1': 0}. Best is trial 1 with value: 4.440892098500626e-16.
[I 2024-11-16 14:49:12,264] Trial 2 finished with value: 7.9889108105187 and parameters: {'x_0': 3, 'x_1': 2}. Best is trial 1 with value: 4.440892098500626e-16.
[I 2024-11-16 14:49:12,265] Trial 3 finished with value: 3.6253849384403627 and parameters: {'x_0': 1, 'x_1': 1}. Best is trial 1 with value: 4.440892098500626e-16.
[I 2024-11-16 14:49:12,266]

Categorical Inputs:
Best value: 4.440892098500626e-16
Best params: {'x_0': 0, 'x_1': 0}

Integer Inputs:
Best value: 4.440892098500626e-16
Best params: {'x_0': 0, 'x_1': 0}


In [15]:
optuna.visualization.plot_optimization_history(study_categorical)

In [16]:
optuna.visualization.plot_optimization_history(study_int)

In [17]:
import numpy as np
import optuna
from functools import partial

from _src import CustomGPSampler


def ackley(x):
    """
    Computes the d-dimensional Ackley function.
    :param x: np.array, shape (d,) - point at which to evaluate the function.
    :return: float - value of the Ackley function at x.
    """
    a = 20
    b = 0.2
    c = 2 * np.pi
    d = len(x)
    sum1 = -a * np.exp(-b * np.sqrt(np.sum(x ** 2) / d))
    sum2 = -np.exp(np.sum(np.cos(c * x)) / d)
    return sum1 + sum2 + a + np.exp(1)

# Define the objective function for categorical inputs
def objective_categorical(trial, dimensions):
    categories = list(range(-5, 6))  # Categorical values from -5 to 5
    x = np.array([trial.suggest_categorical(f"x_{i}", categories) for i in range(dimensions)])
    return ackley(x)

# Define the objective function for integer inputs
def objective_int(trial, dimensions):
    x = np.array([trial.suggest_int(f"x_{i}", -5, 5) for i in range(dimensions)])
    return ackley(x)

# Function to run Bayesian optimization
def run_bo(objective_function, dimensions, n_trials, seed):
    sampler = CustomGPSampler(seed=seed)
    study = optuna.create_study(sampler=sampler, direction="minimize")
    objective_with_args = partial(objective_function, dimensions=dimensions)
    study.optimize(objective_with_args, n_trials=n_trials)
    return study

# Parameters
dimensions = 5
n_trials = 300
seed = 0

# Run optimization with categorical inputs
study_categorical = run_bo(objective_categorical, dimensions, n_trials, seed)

# Run optimization with integer inputs
study_int = run_bo(objective_int, dimensions, n_trials, seed)

# Print best results
print("Categorical Inputs:")
print(f"Best value: {study_categorical.best_value}")
print(f"Best params: {study_categorical.best_params}")

print("\nInteger Inputs:")
print(f"Best value: {study_int.best_value}")
print(f"Best params: {study_int.best_params}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_2960/1471992206.py:35: ExperimentalWarning:

CustomGPSampler is experimental (supported from v3.6.0). The interface can change in the future.

[I 2024-11-16 14:50:12,596] A new study created in memory with name: no-name-27a9855e-65d5-425a-8e67-a4cf071f6520
[I 2024-11-16 14:50:12,598] Trial 0 finished with value: 8.127840976905148 and parameters: {'x_0': 3, 'x_1': 4, 'x_2': 0, 'x_3': 0, 'x_4': 3}. Best is trial 0 with value: 8.127840976905148.
[I 2024-11-16 14:50:12,599] Trial 1 finished with value: 6.976179046166793 and parameters: {'x_0': 2, 'x_1': 1, 'x_2': 1, 'x_3': -4, 'x_4': -1}. Best is trial 1 with value: 6.976179046166793.
[I 2024-11-16 14:50:12,601] Trial 2 finished with value: 9.996730890438618 and parameters: {'x_0': 3, 'x_1': -4, 'x_2': 3, 'x_3': 1, 'x_4': 5}. Best is trial 1 with value: 6.976179046166793.
[I 2024-11-16 14:50:12,602] Trial 3 finished with value: 9.697286414061548 and parameters: {'x_0': -5, 'x_1': 3

Categorical Inputs:
Best value: 4.440892098500626e-16
Best params: {'x_0': 0, 'x_1': 0, 'x_2': 0, 'x_3': 0, 'x_4': 0}

Integer Inputs:
Best value: 4.21454285630703
Best params: {'x_0': 1, 'x_1': 2, 'x_2': 1, 'x_3': 0, 'x_4': -1}


In [18]:
optuna.visualization.plot_optimization_history(study_categorical)

In [19]:
optuna.visualization.plot_optimization_history(study_int)