In [1]:
import numpy as np

In [3]:
n = 3
m = 5

tensor  = np.zeros((n,) * m)

tensor.shape

(3, 3, 3, 3, 3)

In [12]:
import numpy as np
import time

n = 11
m = 7

tensor = np.zeros((n,) * m)

start_time = time.time()

cnt = 0

for x in np.nditer(tensor):
    pass  # Replace this with any operation you want to perform on each entry
    if 1 == 1:
        cnt += 1

end_time = time.time()

print(f"Time taken for the loop: {end_time - start_time} seconds")
print(f"Count: {cnt}")

Time taken for the loop: 1.4843981266021729 seconds
Count: 19487171


In [23]:
import numpy as np

n = 2
m = 3

tensor = np.zeros((n,) * m)
tensor

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
indices = np.indices(tensor.shape)
indices

array([[[[0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1]]],


       [[[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]]],


       [[[0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1]]]])

In [18]:
index_sum = np.sum(indices, axis=0)
index_sum

array([[[[[[[ 0,  1,  2, ...,  8,  9, 10],
            [ 1,  2,  3, ...,  9, 10, 11],
            [ 2,  3,  4, ..., 10, 11, 12],
            ...,
            [ 8,  9, 10, ..., 16, 17, 18],
            [ 9, 10, 11, ..., 17, 18, 19],
            [10, 11, 12, ..., 18, 19, 20]],

           [[ 1,  2,  3, ...,  9, 10, 11],
            [ 2,  3,  4, ..., 10, 11, 12],
            [ 3,  4,  5, ..., 11, 12, 13],
            ...,
            [ 9, 10, 11, ..., 17, 18, 19],
            [10, 11, 12, ..., 18, 19, 20],
            [11, 12, 13, ..., 19, 20, 21]],

           [[ 2,  3,  4, ..., 10, 11, 12],
            [ 3,  4,  5, ..., 11, 12, 13],
            [ 4,  5,  6, ..., 12, 13, 14],
            ...,
            [10, 11, 12, ..., 18, 19, 20],
            [11, 12, 13, ..., 19, 20, 21],
            [12, 13, 14, ..., 20, 21, 22]],

           ...,

           [[ 8,  9, 10, ..., 16, 17, 18],
            [ 9, 10, 11, ..., 17, 18, 19],
            [10, 11, 12, ..., 18, 19, 20],
            ...,
      

In [66]:
from tensorly.decomposition import non_negative_parafac
from tensorly.cp_tensor import cp_to_tensor

tensor = np.random.rand(3, 4, 2)
tensor

array([[[0.44433579, 0.87312019],
        [0.33003098, 0.31852431],
        [0.62709955, 0.15915081],
        [0.36530258, 0.00608282]],

       [[0.53061185, 0.08448109],
        [0.03376937, 0.28970219],
        [0.2102458 , 0.85620734],
        [0.52363311, 0.07458297]],

       [[0.37727369, 0.39468072],
        [0.78094082, 0.75253771],
        [0.78534377, 0.20726312],
        [0.97753167, 0.05301356]]])

In [67]:
decomposed = non_negative_parafac(tensor, rank=2)
decomposed

recovered = cp_to_tensor(decomposed)
recovered

array([[[0.42790718, 0.62458236],
        [0.43783009, 0.46794565],
        [0.46360752, 0.41827642],
        [0.39369434, 0.0421662 ]],

       [[0.29090231, 0.39934069],
        [0.3319891 , 0.30341766],
        [0.36703178, 0.27381644],
        [0.37450286, 0.0401105 ]],

       [[0.45735023, 0.52700246],
        [0.65899211, 0.41834725],
        [0.78399748, 0.38843113],
        [1.01523407, 0.10873431]]])

In [68]:
recovered = cp_to_tensor(decomposed)
recovered

array([[[0.42790718, 0.62458236],
        [0.43783009, 0.46794565],
        [0.46360752, 0.41827642],
        [0.39369434, 0.0421662 ]],

       [[0.29090231, 0.39934069],
        [0.3319891 , 0.30341766],
        [0.36703178, 0.27381644],
        [0.37450286, 0.0401105 ]],

       [[0.45735023, 0.52700246],
        [0.65899211, 0.41834725],
        [0.78399748, 0.38843113],
        [1.01523407, 0.10873431]]])

In [92]:
from tensorly.decomposition import non_negative_parafac
from tensorly.cp_tensor import cp_to_tensor

tensor = np.random.randn(n, m, 2)
tensor


array([[[ 0.94026116,  0.23310876],
        [ 1.39918012, -1.1226392 ],
        [ 0.27395997,  0.97854003]],

       [[ 0.41390258,  0.14841226],
        [-0.58913547, -0.31996998],
        [-1.63510105,  1.22379001]]])

In [93]:
tensor_exp = np.exp(tensor)
tensor_exp

array([[[2.56065007, 1.26251878],
        [4.05187653, 0.32541981],
        [1.31516215, 2.66056906]],

       [[1.51270976, 1.15999102],
        [0.55480672, 0.72617084],
        [0.19493267, 3.40004956]]])

In [94]:
tensor_exp_decomposed = non_negative_parafac(tensor_exp, rank=2)
tensor_exp_decomposed

(weights, factors) : rank-2 CPTensor of shape (2, 3, 2)

In [95]:
tensor_exp_recovered = cp_to_tensor(tensor_exp_decomposed)
tensor_exp_recovered

array([[[2.7575918 , 1.08351799],
        [3.93243149, 0.49033959],
        [1.25566781, 2.70287263]],

       [[0.74454794, 1.32767341],
        [1.02005871, 0.57843994],
        [0.42636858, 3.35882867]]])

In [96]:
tensor_recovered = np.log(tensor_exp_recovered)
tensor_recovered

array([[[ 1.01435776,  0.08021314],
        [ 1.36925793, -0.71265708],
        [ 0.22766755,  0.99431514]],

       [[-0.29497804,  0.28342809],
        [ 0.01986019, -0.54742056],
        [-0.85245111,  1.2115923 ]]])

In [97]:
np.linalg.norm(tensor - tensor_recovered)

np.float64(1.3252471850581797)

In [113]:
from tensorly.decomposition import parafac
from tensorly.cp_tensor import cp_to_tensor

tensor = np.random.randn(n, m, 2)
tensor

array([[[-0.73952343, -0.14668274],
        [-0.08201242, -0.13337246],
        [ 0.33112256,  0.19832454]],

       [[-0.37849784, -0.75616019],
        [ 1.03465093,  0.69981049],
        [ 0.34625379,  1.12428842]]])

In [114]:
tensor[1, 2, 1] = -100000
tensor

array([[[-7.39523427e-01, -1.46682744e-01],
        [-8.20124217e-02, -1.33372456e-01],
        [ 3.31122562e-01,  1.98324543e-01]],

       [[-3.78497837e-01, -7.56160189e-01],
        [ 1.03465093e+00,  6.99810493e-01],
        [ 3.46253785e-01, -1.00000000e+05]]])

In [115]:
decomposed = parafac(tensor, rank=2)
decomposed

(weights, factors) : rank-2 CPTensor of shape (2, 3, 2)

In [116]:
tensor_recovered = cp_to_tensor(decomposed)
tensor_recovered

array([[[-1.98634354e-01,  1.25976107e-02],
        [ 3.16781042e-01, -2.00895200e-02],
        [ 2.72821375e-01,  1.96981375e-01]],

       [[-5.71018073e-01, -7.54240970e-01],
        [ 9.10654457e-01,  6.96752288e-01],
        [ 3.46254246e-01, -1.00000000e+05]]])

In [117]:
np.linalg.norm(tensor - tensor_recovered)

np.float64(0.7386836308854469)

In [118]:
import numpy as np

# Define a sample constraint function
def constraint_function(value):
    # Example constraint: Values must be >= 0, otherwise mark as -10
    return value if value >= 0 else -10

# Create a sample tensor (e.g., trial evaluations)
sample_tensor = np.array([
    [0.5, -0.2, 1.0],
    [1.5, -1.0, 0.0],
    [-0.3, 0.7, -0.1]
])

# Apply the constraint function element-wise using np.vectorize
tensor_constraint = np.vectorize(constraint_function)(sample_tensor)

# Display the original tensor and the constrained tensor
print("Original Tensor:")
print(sample_tensor)

print("\nConstrained Tensor:")
print(tensor_constraint)


Original Tensor:
[[ 0.5 -0.2  1. ]
 [ 1.5 -1.   0. ]
 [-0.3  0.7 -0.1]]

Constrained Tensor:
[[  0.5 -10.    1. ]
 [  1.5 -10.    0. ]
 [-10.    0.7 -10. ]]


In [129]:
temp = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

temp

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [130]:
np.argwhere(temp == 1)

array([[0, 0],
       [0, 2],
       [1, 1],
       [2, 0],
       [2, 2]])

In [126]:
rand = np.random.rand(3, 3)
rand

array([[0.38156836, 0.7857061 , 0.11745597],
       [0.58248796, 0.24340843, 0.70743719],
       [0.89646165, 0.60903213, 0.56129966]])

In [127]:
rand[np.argwhere(temp)] = -100

In [133]:
temp

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [128]:
rand

array([[-100., -100., -100.],
       [-100., -100., -100.],
       [-100., -100., -100.]])

In [131]:
rand[temp] = 999

In [132]:
rand

array([[ 999.,  999.,  999.],
       [ 999.,  999.,  999.],
       [-100., -100., -100.]])

In [135]:
tttt = np.where(temp == 1, -412, rand)

In [136]:
tttt

array([[-412.,  999., -412.],
       [ 999., -412.,  999.],
       [-412., -100., -412.]])

In [1]:
import numpy as np

directions_list = ["oo", "ab", "ac", "ad", "bc", "bd", "cd"]
directions_list.index("cd")

6

In [2]:
directions_dict = {
    "oo": (0, 0),
    "ab": (1, 1),
    "ac": (0, 2),
    "ad": (1, 1),
    "bc": (1, 1),
    "bd": (2, 0),
    "cd": (1, 1)
}

In [66]:
# constraint 1: (0, 0) != "oo", "ab"
# constraint 2: (map_shape[0] - 1, map_shape[1] - 1) != "oo", "cd"
# constraint 3: len[path] == map_shape[0] * map_shape[1]

directions_dict = {
    "oo": np.array([0, 0]),
    "ab": np.array([1, 1]),
    "ac": np.array([0, 2]),
    "ad": np.array([1, 1]),
    "bc": np.array([1, 1]),
    "bd": np.array([2, 0]),
    "cd": np.array([1, 1])
}

directions_list = list(directions_dict.keys())

map_shape = (2, 3)
map_length = map_shape[0] * map_shape[1]
ideal_gain = (map_shape[0] + map_shape[1] - 1) * 2

tensor_constraint_1 = np.zeros((len(directions_list),) * map_length)

for direction in directions_list:
    if direction not in ["oo", "ab"]:
        tensor_constraint_1[:, :, :, :, :, directions_list.index(direction)] = 1

tensor_constraint_2 = np.zeros((len(directions_list),) * map_length)

for direction in directions_list:
    if direction not in ["oo", "cd"]:
        tensor_constraint_2[directions_list.index(direction), :, :, :, :, :] = 1


tensor_constraint_3 = np.zeros((len(directions_list),) * map_length)
for index, entry in np.ndenumerate(tensor_constraint_3):
    gain = np.sum([directions_dict.get(directions_list[idx], 0) for idx in index])

    if gain == ideal_gain:
        tensor_constraint_3[index] = 1


tensor_constraint = np.logical_and(tensor_constraint_1, tensor_constraint_2, tensor_constraint_3)



import torch

def build_constraint_constraint() -> torch.Tensor:

    return tensor_constraint

In [74]:
import torch

def build_constraint_warcraft() -> torch.Tensor:
    # Directions dictionary
    directions_dict = {
        "oo": torch.tensor([0, 0]),
        "ab": torch.tensor([1, 1]),
        "ac": torch.tensor([0, 2]),
        "ad": torch.tensor([1, 1]),
        "bc": torch.tensor([1, 1]),
        "bd": torch.tensor([2, 0]),
        "cd": torch.tensor([1, 1]),
    }

    directions_list = list(directions_dict.keys())

    # Map parameters
    map_shape = (2, 3)
    map_length = map_shape[0] * map_shape[1]
    ideal_gain = (map_shape[0] + map_shape[1] - 1) * 2

    # Initialize constraints as PyTorch tensors
    tensor_constraint_1 = torch.zeros((len(directions_list),) * map_length)
    tensor_constraint_2 = torch.zeros((len(directions_list),) * map_length)
    tensor_constraint_3 = torch.zeros((len(directions_list),) * map_length)

    # Constraint 1: (0, 0) != "oo", "ab"
    for direction in directions_list:
        if direction not in ["oo", "ab"]:
            tensor_constraint_1[..., directions_list.index(direction)] = 1

    # Constraint 2: (map_shape[0] - 1, map_shape[1] - 1) != "oo", "cd"
    for direction in directions_list:
        if direction not in ["oo", "cd"]:
            tensor_constraint_2[directions_list.index(direction), ...] = 1

    # Constraint 3: len[path] == map_shape[0] * map_shape[1]
    for index in torch.cartesian_prod(*[torch.arange(len(directions_list)) for _ in range(map_length)]):
        index_tuple = tuple(index.tolist())
        gain = sum(directions_dict[directions_list[idx]].sum().item() for idx in index_tuple)
        if gain == ideal_gain:
            tensor_constraint_3[index_tuple] = 1

    # Combine constraints with logical AND
    tensor_constraint = torch.logical_and(
        tensor_constraint_1, 
        torch.logical_and(tensor_constraint_2, tensor_constraint_3)
    )

    return tensor_constraint.float()


tensor_constraint = build_constraint_warcraft()
tensor_constraint

tensor([[[[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]],

           [[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]],

           [[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]],

           ...,

           [[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
  

In [71]:
tensor_constraint

tensor([[[[[[False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            ...,
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False]],

           [[False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            ...,
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False]],

           [[False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            [False, False, False,  ..., False, False, False],
            ...,
            [Fa

In [69]:
tensor_constraint.sum()

tensor(5400.)

In [59]:
tensor_constraint_1.sum()

np.float64(84035.0)

In [60]:
tensor_constraint_2.sum()

np.float64(84035.0)

In [58]:
tensor_constraint_3.sum()

np.float64(19440.0)

In [57]:
7 ** 6

117649

In [62]:
tensor_constraint = np.logical_and.reduce((tensor_constraint_1, tensor_constraint_2, tensor_constraint_3))

tensor_constraint.sum()

np.int64(5400)

In [64]:
int(tensor_constraint.sum()) / 7 ** 6

0.04589924266249607

In [ ]:
def 