In [1]:
import numpy as np

seed = 0

rng = np.random.RandomState(seed)

rng

RandomState(MT19937) at 0x115475D40

In [2]:
for _ in range(5):
    display(rng.rand(3))

array([0.5488135 , 0.71518937, 0.60276338])

array([0.54488318, 0.4236548 , 0.64589411])

array([0.43758721, 0.891773  , 0.96366276])

array([0.38344152, 0.79172504, 0.52889492])

array([0.56804456, 0.92559664, 0.07103606])

In [2]:
for _ in range(5):
    display(rng.rand(3))

array([0.5488135 , 0.71518937, 0.60276338])

array([0.54488318, 0.4236548 , 0.64589411])

array([0.43758721, 0.891773  , 0.96366276])

array([0.38344152, 0.79172504, 0.52889492])

array([0.56804456, 0.92559664, 0.07103606])

In [2]:

for _ in range(5):
    seed = 0
    rng = np.random.RandomState(seed)

    display(rng.rand(3))

array([0.5488135 , 0.71518937, 0.60276338])

array([0.5488135 , 0.71518937, 0.60276338])

array([0.5488135 , 0.71518937, 0.60276338])

array([0.5488135 , 0.71518937, 0.60276338])

array([0.5488135 , 0.71518937, 0.60276338])